# Generated by Django 5.1.4 on 2024-12-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressReport',
        ),
    ]
